import { useState, useEffect } from 'react';
import { DollarSign, ArrowUpRight, ArrowDownRight, TrendingUp, TrendingDown, Target } from 'lucide-react';
import { motion } from 'framer-motion';
import { MarketTabs, ALL_MARKET_TABS, useMarket } from '../components/MarketTabs';
import { API_BASE } from '../config';

export const MoneyTracker = () => {
  const [market] = useMarket('US');
  const [data, setData] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  const fetchTracker = async () => {
    try {
      const activeApiBase =
        market === 'INDIA'  ? `${API_BASE}/indian`  :
        market === 'STOCKS' ? `${API_BASE}/stocks`   :
        market === 'CRYPTO' ? `${API_BASE}/crypto`   :
        market === 'FOREX'  ? `${API_BASE}/forex`    :
        API_BASE;
      const res = await fetch(`${activeApiBase}/portfolio/money-tracker`);
      if (res.ok) {
        const json = await res.json();
        setData(json);
      }
    } catch (e) {
      console.error('Failed to fetch money tracker data');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTracker();
    const interval = setInterval(fetchTracker, 5000);
    return () => clearInterval(interval);
  }, [market]);

  if (loading && !data) {
    return (
      <div className="flex items-center justify-center h-full">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-theme_blue"></div>
      </div>
    );
  }

  const { summary = {}, closed_trades = [], active_holdings = [] } = data || {};

  const investedCapital = active_holdings.reduce((sum: number, h: any) => sum + (h.shares * h.entry_price), 0);
  const currentBalance = summary.current_balance || 0;
  const initialCapital = currentBalance + investedCapital - (summary.total_pnl || 0);

  return (
    <div className="max-w-7xl mx-auto space-y-8 pb-12">
      <div className="flex flex-col gap-4">
        <div>
          <h1 className="font-display text-4xl md:text-5xl font-bold tracking-tight mb-2 flex items-center gap-3">
            <DollarSign className="w-10 h-10 text-emerald-500" /> Money Tracker
          </h1>
          <p className="text-muted-foreground text-lg">
            Full detailed breakdown of every realized profit and loss generated by the AI Engine.
          </p>
        </div>
        <MarketTabs tabs={ALL_MARKET_TABS} />
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-theme_blue/10 border border-theme_blue/20 rounded-2xl p-6 shadow-sm">
          <p className="text-sm font-bold text-theme_blue uppercase tracking-wider mb-2">Available Cash</p>
          <div className="flex items-center gap-2">
            <span className="text-4xl font-display font-bold text-theme_blue">
              {market === 'INDIA' ? '₹' : '$'}{currentBalance.toFixed(2)}
            </span>
          </div>
        </div>

        <div className="bg-purple-600/10 border border-purple-600/20 rounded-2xl p-6 shadow-sm">
          <p className="text-sm font-bold text-purple-600 uppercase tracking-wider mb-2">Invested Capital (Active)</p>
          <div className="flex items-center gap-2">
            <span className="text-4xl font-display font-bold text-purple-600">
              {market === 'INDIA' ? '₹' : '$'}{investedCapital.toFixed(2)}
            </span>
          </div>
          <p className="text-xs font-bold text-purple-600/70 mt-2">{active_holdings.length} Active Positions</p>
        </div>

        <div className="bg-card border border-border rounded-2xl p-6 shadow-sm">
          <p className="text-sm font-bold text-muted-foreground uppercase tracking-wider mb-2">Total Portfolio Value</p>
          <div className="flex items-center gap-2">
            <span className="text-4xl font-display font-bold text-foreground">
              {market === 'INDIA' ? '₹' : '$'}{(currentBalance + investedCapital).toFixed(2)}
            </span>
          </div>
          <p className="text-xs font-bold text-muted-foreground mt-2">Started with {market === 'INDIA' ? '₹' : '$'}{initialCapital.toFixed(2)}</p>
        </div>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-card border border-border rounded-2xl p-6 shadow-sm">
          <p className="text-sm font-bold text-muted-foreground uppercase tracking-wider mb-2">Net Profit (PnL)</p>
          <div className="flex items-center gap-2">
            <span className={`text-3xl font-display font-bold ${summary.total_pnl >= 0 ? 'text-emerald-500' : 'text-red-500'}`}>
              {summary.total_pnl >= 0 ? '+' : ''}{market === 'INDIA' ? '₹' : '$'}{summary.total_pnl?.toFixed(2) || '0.00'}
            </span>
          </div>
        </div>

        <div className="bg-card border border-border rounded-2xl p-6 shadow-sm">
          <p className="text-sm font-bold text-muted-foreground uppercase tracking-wider mb-2">Gross Profit</p>
          <div className="flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-emerald-500" />
            <span className="text-3xl font-display font-bold text-emerald-500">
              +{market === 'INDIA' ? '₹' : '$'}{summary.gross_profit?.toFixed(2) || '0.00'}
            </span>
          </div>
        </div>

        <div className="bg-card border border-border rounded-2xl p-6 shadow-sm">
          <p className="text-sm font-bold text-muted-foreground uppercase tracking-wider mb-2">Gross Loss</p>
          <div className="flex items-center gap-2">
            <TrendingDown className="w-5 h-5 text-red-500" />
            <span className="text-3xl font-display font-bold text-red-500">
              {market === 'INDIA' ? '₹' : '$'}{summary.gross_loss?.toFixed(2) || '0.00'}
            </span>
          </div>
        </div>

        <div className="bg-card border border-border rounded-2xl p-6 shadow-sm">
          <p className="text-sm font-bold text-muted-foreground uppercase tracking-wider mb-2">Win Rate</p>
          <div className="flex items-center gap-2">
            <Target className="w-5 h-5 text-theme_blue" />
            <span className="text-3xl font-display font-bold">
              {summary.win_rate?.toFixed(1) || '0.0'}%
            </span>
          </div>
        </div>
      </div>

      <div className="bg-purple-600/5 border border-purple-600/20 rounded-3xl overflow-hidden shadow-sm">
        <div className="p-6 border-b border-purple-600/10 flex justify-between items-center bg-purple-600/5">
          <h2 className="text-xl font-display font-bold text-purple-600">Active Investments Detail</h2>
          <div className="flex items-center gap-3">
            <span className="text-sm text-purple-600/70 font-bold">{active_holdings.length} Active</span>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-purple-600/5 border-b border-purple-600/10 text-xs uppercase tracking-wider font-bold text-purple-600/70">
                <th className="px-6 py-4">Asset</th>
                <th className="px-6 py-4">Qty</th>
                <th className="px-6 py-4">Avg Entry</th>
                <th className="px-6 py-4 text-right">Invested ({market === 'INDIA' ? '₹' : '$'})</th>
                <th className="px-6 py-4 text-right">Target / Stop</th>
              </tr>
            </thead>
            <tbody>
              {active_holdings.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-6 py-12 text-center text-purple-600/50 font-medium">
                    No active investments right now. AI is waiting for a signal!
                  </td>
                </tr>
              ) : (
                [...active_holdings].map((trade: any, idx: number) => (
                  <motion.tr 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.05 }}
                    key={idx} 
                    className="border-b border-purple-600/10 hover:bg-purple-600/5 transition-colors"
                  >
                    <td className="px-6 py-4 font-bold text-foreground">
                      <div className="flex items-center gap-2">
                        {trade.symbol}
                        <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold ${
                          trade.direction === 'SHORT' ? 'bg-red-500/10 text-red-500 border border-red-500/20' : 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20'
                        }`}>
                          {trade.direction === 'SHORT' ? 'SHORT' : 'LONG'}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-foreground">
                      {trade.shares}
                    </td>
                    <td className="px-6 py-4">
                      {market === 'INDIA' ? '₹' : '$'}{Number(trade.entry_price || 0).toFixed(2)}
                    </td>
                    <td className="px-6 py-4 text-right font-bold text-purple-600">
                      {market === 'INDIA' ? '₹' : '$'}{(Number(trade.shares || 0) * Number(trade.entry_price || 0)).toFixed(2)}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex flex-col items-end gap-1">
                        <span className="text-xs font-bold text-emerald-500">T: {market === 'INDIA' ? '₹' : '$'}{Number(trade.take_profit || 0).toFixed(2)}</span>
                        <span className="text-xs font-bold text-red-500">S: {market === 'INDIA' ? '₹' : '$'}{Number(trade.stop_loss || 0).toFixed(2)}</span>
                      </div>
                    </td>
                  </motion.tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      <div className="bg-card border border-border rounded-3xl overflow-hidden shadow-sm">
        <div className="p-6 border-b border-border flex justify-between items-center bg-muted/20">
          <h2 className="text-xl font-display font-bold">Closed Trades Detail</h2>
          <div className="flex items-center gap-3">
            <span className="text-sm text-muted-foreground font-bold">{summary.total_trades} Trades</span>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-muted/30 border-b border-border text-xs uppercase tracking-wider font-bold text-muted-foreground">
                <th className="px-6 py-4">Time</th>
                <th className="px-6 py-4">Asset</th>
                <th className="px-6 py-4">Qty</th>
                <th className="px-6 py-4">Entry</th>
                <th className="px-6 py-4">Exit</th>
                <th className="px-6 py-4 text-right">Profit / Loss</th>
                <th className="px-6 py-4 text-right">Return %</th>
              </tr>
            </thead>
            <tbody>
              {closed_trades.length === 0 ? (
                <tr>
                  <td colSpan={7} className="px-6 py-12 text-center text-muted-foreground font-medium">
                    No closed trades yet. The AI is scanning the markets!
                  </td>
                </tr>
              ) : (
                [...closed_trades].reverse().map((trade: any, idx: number) => (
                  <motion.tr 
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: idx * 0.05 }}
                    key={idx} 
                    className="border-b border-border hover:bg-muted/10 transition-colors"
                  >
                    <td className="px-6 py-4 text-sm font-medium">
                      {new Date(trade.time * 1000).toLocaleTimeString()}
                    </td>
                    <td className="px-6 py-4 font-bold">
                      <div className="flex items-center gap-2">
                        {trade.symbol}
                        <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-bold ${
                          trade.direction === 'SHORT' ? 'bg-red-500/10 text-red-500 border border-red-500/20' : 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20'
                        }`}>
                          {trade.direction === 'SHORT' ? 'SHORT' : 'LONG'}
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm">
                      {trade.shares}
                    </td>
                    <td className="px-6 py-4 text-sm">
                      {market === 'INDIA' ? '₹' : '$'}{Number(trade.entry_price || 0).toFixed(2)}
                    </td>
                    <td className="px-6 py-4 text-sm">
                      {market === 'INDIA' ? '₹' : '$'}{Number(trade.exit_price || 0).toFixed(2)}
                    </td>
                    {(() => {
                      const pnl = Number(trade.pnl ?? trade.profit_loss ?? 0);
                      return (
                        <td className={`px-6 py-4 text-right font-bold ${pnl >= 0 ? 'text-emerald-500' : 'text-red-500'}`}>
                          {pnl >= 0 ? '+' : ''}{market === 'INDIA' ? '₹' : '$'}{Math.abs(pnl).toFixed(2)}
                        </td>
                      );
                    })()}
                    <td className="px-6 py-4 text-right">
                      <span className={`inline-flex items-center gap-1 px-2 py-1 rounded-md text-xs font-bold ${
                        Number(trade.profit_pct ?? trade.return_pct ?? 0) >= 0 ? 'bg-emerald-500/10 text-emerald-500' : 'bg-red-500/10 text-red-500'
                      }`}>
                        {Number(trade.profit_pct ?? trade.return_pct ?? 0) >= 0 ? <ArrowUpRight className="w-3 h-3" /> : <ArrowDownRight className="w-3 h-3" />}
                        {Math.abs(Number(trade.profit_pct ?? trade.return_pct ?? 0)).toFixed(2)}%
                      </span>
                    </td>
                  </motion.tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
